In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [5]:
from _grids import RecCuboid

In [23]:
from _solver import BoundCond
from _solver import Matrix
from _solver import OnePhase

# Creating Grids

In [7]:
grid = RecCuboid((750,1000,1250),(750,1000,1250),(20,))

In [8]:
grid.xdims

array([[ 750.],
       [1000.],
       [1250.],
       [ 750.],
       [1000.],
       [1250.],
       [ 750.],
       [1000.],
       [1250.]])

In [9]:
grid.volume

array([[11250000.],
       [15000000.],
       [18750000.],
       [15000000.],
       [20000000.],
       [25000000.],
       [18750000.],
       [25000000.],
       [31250000.]])

In [10]:
grid.xaxis

array([ 375., 1250., 2375.])

In [11]:
grid.yaxis

array([ 375., 1250., 2375.])

In [12]:
# grid.set_depth(10000)
grid.set_depth([6400,6000,5600,6000,5800,5400,5600,5400,5200])

In [13]:
grid.depth

array([[6400.],
       [6000.],
       [5600.],
       [6000.],
       [5800.],
       [5400.],
       [5600.],
       [5400.],
       [5200.]])

In [14]:
grid.set_poro((0.15,0.18,0.20,0.17,0.20,0.22,0.22,0.25,0.26))

In [15]:
grid.poro

array([[0.15],
       [0.18],
       [0.2 ],
       [0.17],
       [0.2 ],
       [0.22],
       [0.22],
       [0.25],
       [0.26]])

In [16]:
grid.set_perm((50,100,200,100,150,250,150,200,300),yreduce=0.5,zreduce=0.1)

In [17]:
grid.xperm

array([[ 50.],
       [100.],
       [200.],
       [100.],
       [150.],
       [250.],
       [150.],
       [200.],
       [300.]])

In [18]:
grid.zmin

# Fluid Properties

In [19]:
class fluid():
    
    def __init__(self,density,viscosity):
        """
        density in lbm/ft3
        viscosity in cp
        """
        self._density = density*16.0185
        self._viscosity = viscosity*0.001

    @property
    def density(self):
        return self._density/16.0185
        
    @property
    def viscosity(self):
        return self._viscosity/0.001

In [20]:
oil = fluid(53,5)

In [21]:
oil.density

53.0

In [22]:
oil.viscosity

5.0

# Matrices

In [24]:
bcond = BoundCond('xmax',press=1000)

In [26]:
tclass = Matrix(grid,oil,bconds=(bcond,))

In [27]:
tclass._staticx

array([3.60977066e-13, 5.55349333e-13, 8.49357803e-13, 1.03136305e-12,
       1.50407111e-12, 1.64080485e-12])

In [28]:
tmatrix = tclass.Tmatrix()

In [29]:
tmatrix.todense()

matrix([[ 1.08293120e-10, -7.21954132e-11,  0.00000000e+00,
         -3.60977066e-11,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-7.21954132e-11,  2.68201060e-10, -1.11069867e-10,
          0.00000000e+00, -8.49357803e-11,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -1.11069867e-10,  3.05143558e-10,
          0.00000000e+00,  0.00000000e+00, -1.94073692e-10,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-3.60977066e-11,  0.00000000e+00,  0.00000000e+00,
          2.55193413e-10, -1.69871561e-10,  0.00000000e+00,
         -4.92241454e-11,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -8.49357803e-11,  0.00000000e+00,
         -1.69871561e-10,  5.54235322e-10, -2.06272609e-10,
          0.00000000e+00, -9.31553719e-11,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.94073692e-10,
          0.00000000e+00, -2.062726

In [30]:
jmatrix = tclass.Jmatrix()

In [31]:
jmatrix.todense()

matrix([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 2.88781653e-10, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 4.81302755e-10, 0.00000000e+00, 0.00000000

In [32]:
amatrix = tclass.Amatrix()

In [33]:
amatrix.todense()

matrix([[ 47784.678624 ,      0.       ,      0.       ,      0.       ,
              0.       ,      0.       ,      0.       ,      0.       ,
              0.       ],
        [     0.       ,  76455.4857984,      0.       ,      0.       ,
              0.       ,      0.       ,      0.       ,      0.       ,
              0.       ],
        [     0.       ,      0.       , 106188.17472  ,      0.       ,
              0.       ,      0.       ,      0.       ,      0.       ,
              0.       ],
        [     0.       ,      0.       ,      0.       ,  72207.9588096,
              0.       ,      0.       ,      0.       ,      0.       ,
              0.       ],
        [     0.       ,      0.       ,      0.       ,      0.       ,
         113267.386368 ,      0.       ,      0.       ,      0.       ,
              0.       ],
        [     0.       ,      0.       ,      0.       ,      0.       ,
              0.       , 155742.656256 ,      0.       ,      0.   

In [34]:
qvector = tclass.Qvector()

In [35]:
qvector.todense()

matrix([[0.        ],
        [0.        ],
        [0.00199108],
        [0.        ],
        [0.        ],
        [0.00331847],
        [0.        ],
        [0.        ],
        [0.0049777 ]])

In [36]:
gvector = tclass.Gvector(tmatrix)

In [37]:
gvector

array([[ 1.09928350e-04],
       [ 8.25706160e-05],
       [-1.42449199e-05],
       [ 9.95429624e-05],
       [ 1.74621885e-04],
       [-2.14412951e-04],
       [ 1.02710832e-04],
       [-8.06821795e-05],
       [-2.60034595e-04]])

# Mixed Solver

In [38]:
solver = OnePhase(grid,oil,bconds=(bcond,))

# Time Control

In [39]:
solver.set_time(5,nstep=100)

In [40]:
solver.nstep

100

# Reservoir Initialization

In [41]:
solver.initialize(6400,3000,ctotal=1e-5)

In [42]:
solver.pinit

array([[3000.        ],
       [2852.77224457],
       [2705.54448915],
       [2852.77224457],
       [2779.15836686],
       [2631.93061143],
       [2705.54448915],
       [2631.93061143],
       [2558.31673372]])

# Solving

In [43]:
solver.solve()

0 time step is complete...
1 time step is complete...
2 time step is complete...
3 time step is complete...
4 time step is complete...
5 time step is complete...
6 time step is complete...
7 time step is complete...
8 time step is complete...
9 time step is complete...
10 time step is complete...
11 time step is complete...
12 time step is complete...
13 time step is complete...
14 time step is complete...
15 time step is complete...
16 time step is complete...
17 time step is complete...
18 time step is complete...
19 time step is complete...
20 time step is complete...
21 time step is complete...
22 time step is complete...
23 time step is complete...
24 time step is complete...
25 time step is complete...
26 time step is complete...
27 time step is complete...
28 time step is complete...
29 time step is complete...
30 time step is complete...
31 time step is complete...
32 time step is complete...
33 time step is complete...
34 time step is complete...
35 time step is complete...
36

In [44]:
solver.pressure[:,0]

array([2939.49817745, 2668.32415371, 2027.05417444, 2771.27298048,
       2577.98257892, 1952.57340371, 2620.26664363, 2434.86030827,
       1903.10962596])

In [45]:
solver.pressure[:,1]

array([2827.18284483, 2453.3959482 , 1679.72312893, 2633.9071309 ,
       2356.86032886, 1620.97457967, 2478.43060356, 2218.55957728,
       1585.09866434])

In [46]:
solver.pressure[:,2]

array([2685.94903648, 2257.21947899, 1490.30917894, 2474.03543648,
       2161.80974005, 1443.67490336, 2315.45208954, 2027.50987167,
       1415.17359686])

In [47]:
solver.pressure[:,-1]

array([1364.9778214 , 1208.71550926, 1037.25970896, 1235.81904316,
       1159.10502382, 1005.2223693 , 1112.54026992, 1042.84528493,
        981.61461331])