In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [3]:
from _grids import RecCuboid

In [4]:
from onephase import MixedSolver

# Creating Grids

In [5]:
grid = RecCuboid((750,1000,1250),(750,1000,1250),(20,))

In [6]:
grid.size

array([[ 750.,  750.,   20.],
       [1000.,  750.,   20.],
       [1250.,  750.,   20.],
       [ 750., 1000.,   20.],
       [1000., 1000.,   20.],
       [1250., 1000.,   20.],
       [ 750., 1250.,   20.],
       [1000., 1250.,   20.],
       [1250., 1250.,   20.]])

In [7]:
grid.set_porosity((0.15,0.18,0.20,0.17,0.20,0.22,0.22,0.25,0.26))

In [8]:
grid.poro

array([[0.15],
       [0.18],
       [0.2 ],
       [0.17],
       [0.2 ],
       [0.22],
       [0.22],
       [0.25],
       [0.26]])

In [9]:
grid.set_permeability((50,100,200,100,150,250,150,200,300),yreduce=0.5,zreduce=0.1)

In [10]:
grid.perm

array([[ 50.,  25.,   5.],
       [100.,  50.,  10.],
       [200., 100.,  20.],
       [100.,  50.,  10.],
       [150.,  75.,  15.],
       [250., 125.,  25.],
       [150.,  75.,  15.],
       [200., 100.,  20.],
       [300., 150.,  30.]])

# Fluid Properties

In [11]:
class fluid():
    
    def __init__(self,viscosity):
        """viscosity in cp"""
        self._viscosity = viscosity*0.001
        
    @property
    def viscosity(self):
        return self._viscosity/0.001

In [12]:
oil = fluid(5)

# Mixed Solver

In [13]:
solver = MixedSolver(grid,oil)

In [14]:
solver.set_Tmatrix()

In [15]:
solver.tclass.array(oil)*24*60*60*6894.76*3.28084**3

array([[1.26565812, 1.51878975, 0.63282906, 0.75939487],
       [1.51878975, 2.33659961, 1.68754416, 1.78681147],
       [2.33659961, 3.03757949, 4.2188604 , 4.08276813],
       [3.37508832, 3.57362293, 0.75939487, 1.03553846],
       [3.57362293, 4.33939927, 1.78681147, 1.9597287 ],
       [4.33939927, 5.06263248, 4.08276813, 3.87446364],
       [6.32829061, 6.32829061, 1.03553846, 1.13909231],
       [6.32829061, 6.90358975, 1.9597287 , 2.02505299],
       [6.90358975, 7.59394873, 3.87446364, 3.79697436]])

In [16]:
solver.T.todense()

matrix([[ 2.27818462, -1.51878975,  0.        , -0.75939487,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [-1.51878975,  5.64220082, -2.33659961,  0.        , -1.78681147,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -2.33659961,  6.41936774,  0.        ,  0.        ,
         -4.08276813,  0.        ,  0.        ,  0.        ],
        [-0.75939487,  0.        ,  0.        ,  5.36855627, -3.57362293,
          0.        , -1.03553846,  0.        ,  0.        ],
        [ 0.        , -1.78681147,  0.        , -3.57362293, 11.65956237,
         -4.33939927,  0.        , -1.9597287 ,  0.        ],
        [ 0.        ,  0.        , -4.08276813,  0.        , -4.33939927,
         12.29663104,  0.        ,  0.        , -3.87446364],
        [ 0.        ,  0.        ,  0.        , -1.03553846,  0.        ,
          0.        ,  7.36382907, -6.32829061,  0.        ],
        [ 0.        ,  0.        ,  0.        , 