In [1]:
import numpy as np

In [2]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [3]:
from _grids import RecCuboid
from _fluid import Fluid

In [4]:
from _solver import BoundCond
from _solver import Matrix
from _solver import OnePhase

In [5]:
grid = RecCuboid(dims=(4000,100,100),num=(4,1,1))

In [6]:
grid.set_depth([2059,1559,1059,559])
grid.set_poro(0.25)
grid.set_perm(15)

In [7]:
grid.depth

array([[2059.],
       [1559.],
       [1059.],
       [ 559.]])

In [8]:
grid.xperm

array([[15.],
       [15.],
       [15.],
       [15.]])

In [9]:
grid.poro

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])

In [10]:
water = Fluid(density=62.4,viscosity=1)

In [11]:
water.viscosity

1

In [12]:
bcond = BoundCond('xmax',press=500)

In [13]:
sol = OnePhase(grid,water,bconds=(bcond,))

In [14]:
sol.set_time(1,nstep=2)

In [15]:
sol.initialize(2309,1000,1e-5)

In [16]:
tmatrix = sol.Tmatrix()

In [17]:
tmatrix.todense()*sol.trans2field

matrix([[ 0.94924359, -0.94924359,  0.        ,  0.        ],
        [-0.94924359,  1.89848718, -0.94924359,  0.        ],
        [ 0.        , -0.94924359,  1.89848718, -0.94924359],
        [ 0.        ,  0.        , -0.94924359,  0.94924359]])

In [18]:
sol.Amatrix().todense()*sol.trans2field

matrix([[25.0000024,  0.       ,  0.       ,  0.       ],
        [ 0.       , 25.0000024,  0.       ,  0.       ],
        [ 0.       ,  0.       , 25.0000024,  0.       ],
        [ 0.       ,  0.       ,  0.       , 25.0000024]])

In [19]:
sol.Jmatrix().todense()*sol.trans2field

matrix([[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.89848718]])

In [20]:
sol.Qvector().todense()*sol.volume2field

matrix([[  0.        ],
        [  0.        ],
        [  0.        ],
        [949.24359084]])

In [21]:
sol.Gvector(tmatrix)*sol.volume2field

array([[ 2.05677175e+02],
       [-9.89627705e-14],
       [ 9.89627705e-14],
       [-2.05677175e+02]])

In [24]:
tmatrix.dot(sol.grid.depth)

array([[ 2.25610666e-08],
       [ 0.00000000e+00],
       [ 3.30872245e-24],
       [-2.25610666e-08]])

In [25]:
sol.grid.depth

array([[2059.],
       [1559.],
       [1059.],
       [ 559.]])

In [22]:
sol.pinit

array([[891.66259506],
       [674.98778519],
       [458.31297532],
       [241.63816544]])

In [23]:
sol.solve()

0 time step is complete...
1 time step is complete...


In [24]:
sol.pressure

array([[891.66340049, 891.66640229],
       [675.00980289, 675.07065006],
       [458.93608033, 460.07741527],
       [259.27292611, 275.14324708]])