In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [3]:
from _grids import RecCuboid

In [4]:
from onephase import MixedSolver

# Creating Grids

In [5]:
grid = RecCuboid((750,1000,1250),(750,1000,1250),(20,))

In [6]:
grid.size

array([[ 750.,  750.,   20.],
       [1000.,  750.,   20.],
       [1250.,  750.,   20.],
       [ 750., 1000.,   20.],
       [1000., 1000.,   20.],
       [1250., 1000.,   20.],
       [ 750., 1250.,   20.],
       [1000., 1250.,   20.],
       [1250., 1250.,   20.]])

In [7]:
grid.volume

array([[11250000.],
       [15000000.],
       [18750000.],
       [15000000.],
       [20000000.],
       [25000000.],
       [18750000.],
       [25000000.],
       [31250000.]])

In [8]:
grid.xaxis

array([ 375., 1250., 2375.])

In [9]:
grid.yaxis

array([ 375., 1250., 2375.])

In [10]:
grid.set_depth(10000)

In [11]:
grid.depth

array([[10000.],
       [10000.],
       [10000.],
       [10000.],
       [10000.],
       [10000.],
       [10000.],
       [10000.],
       [10000.]])

In [12]:
grid.set_porosity((0.15,0.18,0.20,0.17,0.20,0.22,0.22,0.25,0.26))

In [13]:
grid.poro

array([[0.15],
       [0.18],
       [0.2 ],
       [0.17],
       [0.2 ],
       [0.22],
       [0.22],
       [0.25],
       [0.26]])

In [14]:
grid.set_permeability((50,100,200,100,150,250,150,200,300),yreduce=0.5,zreduce=0.1)

In [15]:
grid.perm

array([[ 50.,  25.,   5.],
       [100.,  50.,  10.],
       [200., 100.,  20.],
       [100.,  50.,  10.],
       [150.,  75.,  15.],
       [250., 125.,  25.],
       [150.,  75.,  15.],
       [200., 100.,  20.],
       [300., 150.,  30.]])

# Fluid Properties

In [16]:
class fluid():
    
    def __init__(self,viscosity):
        """viscosity in cp"""
        self._viscosity = viscosity*0.001
        
    @property
    def viscosity(self):
        return self._viscosity/0.001

In [17]:
oil = fluid(5)

# Mixed Solver

In [18]:
solver = MixedSolver(grid,oil)

In [19]:
solver.set_Tmatrix()

In [20]:
solver.tclass.array(oil)*24*60*60*6894.76*3.28084**3

array([[1.26565812, 1.51878975, 0.63282906, 0.75939487],
       [1.51878975, 2.33659961, 1.68754416, 1.78681147],
       [2.33659961, 3.03757949, 4.2188604 , 4.08276813],
       [3.37508832, 3.57362293, 0.75939487, 1.03553846],
       [3.57362293, 4.33939927, 1.78681147, 1.9597287 ],
       [4.33939927, 5.06263248, 4.08276813, 3.87446364],
       [6.32829061, 6.32829061, 1.03553846, 1.13909231],
       [6.32829061, 6.90358975, 1.9597287 , 2.02505299],
       [6.90358975, 7.59394873, 3.87446364, 3.79697436]])

In [21]:
solver.T.todense()

matrix([[ 2.27818462, -1.51878975,  0.        , -0.75939487,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [-1.51878975,  5.64220082, -2.33659961,  0.        , -1.78681147,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -2.33659961,  6.41936774,  0.        ,  0.        ,
         -4.08276813,  0.        ,  0.        ,  0.        ],
        [-0.75939487,  0.        ,  0.        ,  5.36855627, -3.57362293,
          0.        , -1.03553846,  0.        ,  0.        ],
        [ 0.        , -1.78681147,  0.        , -3.57362293, 11.65956237,
         -4.33939927,  0.        , -1.9597287 ,  0.        ],
        [ 0.        ,  0.        , -4.08276813,  0.        , -4.33939927,
         12.29663104,  0.        ,  0.        , -3.87446364],
        [ 0.        ,  0.        ,  0.        , -1.03553846,  0.        ,
          0.        ,  7.36382907, -6.32829061,  0.        ],
        [ 0.        ,  0.        ,  0.        , 

In [22]:
type(solver.T)

scipy.sparse._csr.csr_matrix

In [23]:
from scipy.sparse import csr_matrix

In [24]:
a = csr_matrix((5,5))

In [25]:
a.shape

(5, 5)

In [26]:
type(np.array([1,2,3]))

numpy.ndarray

# Time Steps

In [27]:
solver.set_time(5)

In [28]:
solver.nstep

1

# Reservoir Initialization

In [29]:
solver.initialize(pressure=3000,ctotal=1e-5)

In [30]:
solver.pinit

array([[3000.],
       [3000.],
       [3000.],
       [3000.],
       [3000.],
       [3000.],
       [3000.],
       [3000.],
       [3000.]])

# Solving

In [31]:
solver.set_Amatrix()

In [32]:
solver.A.todense()*solver.ctotal

matrix([[ 3.37500032,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  5.40000052,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  7.50000072,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  5.10000049,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  8.00000077,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         11.00000106,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  8.25000079,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , 