In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [3]:
from _grids import RecCuboid

In [4]:
from onephase import Tclass
from onephase import MixedSolver

# Creating Grids

In [5]:
grid = RecCuboid((750,1000,1250),(750,1000,1250),(20,))

In [6]:
grid.size

array([[ 750.,  750.,   20.],
       [1000.,  750.,   20.],
       [1250.,  750.,   20.],
       [ 750., 1000.,   20.],
       [1000., 1000.,   20.],
       [1250., 1000.,   20.],
       [ 750., 1250.,   20.],
       [1000., 1250.,   20.],
       [1250., 1250.,   20.]])

In [7]:
grid.volume

array([[11250000.],
       [15000000.],
       [18750000.],
       [15000000.],
       [20000000.],
       [25000000.],
       [18750000.],
       [25000000.],
       [31250000.]])

In [8]:
grid.xaxis

array([ 375., 1250., 2375.])

In [9]:
grid.yaxis

array([ 375., 1250., 2375.])

In [10]:
# grid.set_depth(10000)
grid.set_depth([6400,6000,5600,6000,5800,5400,5600,5400,5200])

In [11]:
grid.depth

array([[6400.],
       [6000.],
       [5600.],
       [6000.],
       [5800.],
       [5400.],
       [5600.],
       [5400.],
       [5200.]])

In [12]:
grid.set_porosity((0.15,0.18,0.20,0.17,0.20,0.22,0.22,0.25,0.26))

In [13]:
grid.poro

array([[0.15],
       [0.18],
       [0.2 ],
       [0.17],
       [0.2 ],
       [0.22],
       [0.22],
       [0.25],
       [0.26]])

In [14]:
grid.set_permeability((50,100,200,100,150,250,150,200,300),yreduce=0.5,zreduce=0.1)

In [15]:
grid.perm

array([[ 50.,  25.,   5.],
       [100.,  50.,  10.],
       [200., 100.,  20.],
       [100.,  50.,  10.],
       [150.,  75.,  15.],
       [250., 125.,  25.],
       [150.,  75.,  15.],
       [200., 100.,  20.],
       [300., 150.,  30.]])

# Fluid Properties

In [16]:
class fluid():
    
    def __init__(self,density,viscosity):
        """
        density in lbm/ft3
        viscosity in cp
        """
        self._density = density*16.0185
        self._viscosity = viscosity*0.001

    @property
    def density(self):
        return self._density/16.0185
        
    @property
    def viscosity(self):
        return self._viscosity/0.001

In [17]:
oil = fluid(53,5)

In [18]:
oil.density

53.0

In [19]:
oil.viscosity

5.0

# Matrices

In [20]:
tclass = Tclass(grid)

In [21]:
array = tclass.array(oil)

In [22]:
array

array([[6.01628444e-11, 7.21954132e-11, 3.00814222e-11, 3.60977066e-11],
       [7.21954132e-11, 1.11069867e-10, 8.02171258e-11, 8.49357803e-11],
       [1.11069867e-10, 1.44390826e-10, 2.00542815e-10, 1.94073692e-10],
       [1.60434252e-10, 1.69871561e-10, 3.60977066e-11, 4.92241454e-11],
       [1.69871561e-10, 2.06272609e-10, 8.49357803e-11, 9.31553719e-11],
       [2.06272609e-10, 2.40651377e-10, 1.94073692e-10, 1.84171973e-10],
       [3.00814222e-10, 3.00814222e-10, 4.92241454e-11, 5.41465599e-11],
       [3.00814222e-10, 3.28160969e-10, 9.31553719e-11, 9.62605510e-11],
       [3.28160969e-10, 3.60977066e-10, 1.84171973e-10, 1.80488533e-10]])

In [23]:
tmatrix = tclass.T(tclass.Tmatrix(array))

In [24]:
tmatrix.todense()

matrix([[ 2.27818462, -1.51878975,  0.        , -0.75939487,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [-1.51878975,  5.64220082, -2.33659961,  0.        , -1.78681147,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -2.33659961,  6.41936774,  0.        ,  0.        ,
         -4.08276813,  0.        ,  0.        ,  0.        ],
        [-0.75939487,  0.        ,  0.        ,  5.36855627, -3.57362293,
          0.        , -1.03553846,  0.        ,  0.        ],
        [ 0.        , -1.78681147,  0.        , -3.57362293, 11.65956237,
         -4.33939927,  0.        , -1.9597287 ,  0.        ],
        [ 0.        ,  0.        , -4.08276813,  0.        , -4.33939927,
         12.29663104,  0.        ,  0.        , -3.87446364],
        [ 0.        ,  0.        ,  0.        , -1.03553846,  0.        ,
          0.        ,  7.36382907, -6.32829061,  0.        ],
        [ 0.        ,  0.        ,  0.        , 

In [25]:
jmatrix = tclass.J(tclass.Jmatrix(array,(1,1000)))

In [26]:
jmatrix.todense()

matrix([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  6.07515898,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         10.12526497,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , 

In [27]:
amatrix = tclass.A(tclass.Amatrix(5*24*60*60))

In [28]:
amatrix.todense()

matrix([[ 337500.0324    ,       0.        ,       0.        ,
               0.        ,       0.        ,       0.        ,
               0.        ,       0.        ,       0.        ],
        [      0.        ,  540000.05184   ,       0.        ,
               0.        ,       0.        ,       0.        ,
               0.        ,       0.        ,       0.        ],
        [      0.        ,       0.        ,  750000.072     ,
               0.        ,       0.        ,       0.        ,
               0.        ,       0.        ,       0.        ],
        [      0.        ,       0.        ,       0.        ,
          510000.04896   ,       0.        ,       0.        ,
               0.        ,       0.        ,       0.        ],
        [      0.        ,       0.        ,       0.        ,
               0.        ,  800000.0768    ,       0.        ,
               0.        ,       0.        ,       0.        ],
        [      0.        ,       0.        ,      

In [29]:
qvector = tclass.Q(tclass.Qvector(array,(1,1000)))

In [30]:
qvector.todense()

matrix([[    0.        ],
        [    0.        ],
        [ 6075.15898135],
        [    0.        ],
        [    0.        ],
        [10125.26496891],
        [    0.        ],
        [    0.        ],
        [15187.89745337]])

In [31]:
gvector = tclass.G(tclass.Gvector(array,oil))

In [32]:
gvector

array([[ 335.51461161],
       [ 252.01550013],
       [ -43.47721739],
       [ 303.81715276],
       [ 532.96709787],
       [-654.41424319],
       [ 313.48587449],
       [-246.25176366],
       [-793.65701263]])

# Mixed Solver

In [33]:
solver = MixedSolver(grid,oil)

# Time Control

In [34]:
solver.set_time(5,nstep=100)

In [35]:
solver.nstep

100

# Reservoir Initialization

In [36]:
solver.initialize(reference=(6400,3000),ctotal=1e-5)

In [37]:
solver.pinit

array([[3000.        ],
       [2852.72720702],
       [2705.45441404],
       [2852.72720702],
       [2779.09081053],
       [2631.81801755],
       [2705.45441404],
       [2631.81801755],
       [2558.18162107]])

# Solving

In [38]:
solver.solve(((1,1000),))

(9, 9)
(9, 9)
(9, 9)
(9, 1)
(9, 1)
[[ 335.51461161]
 [ 252.01550013]
 [ -43.47721739]
 [ 303.81715276]
 [ 532.96709787]
 [-654.41424319]
 [ 313.48587449]
 [-246.25176366]
 [-793.65701263]]
0 time step is complete...
1 time step is complete...
2 time step is complete...
3 time step is complete...
4 time step is complete...
5 time step is complete...
6 time step is complete...
7 time step is complete...
8 time step is complete...
9 time step is complete...
10 time step is complete...
11 time step is complete...
12 time step is complete...
13 time step is complete...
14 time step is complete...
15 time step is complete...
16 time step is complete...
17 time step is complete...
18 time step is complete...
19 time step is complete...
20 time step is complete...
21 time step is complete...
22 time step is complete...
23 time step is complete...
24 time step is complete...
25 time step is complete...
26 time step is complete...
27 time step is complete...
28 time step is complete...
29 time s

In [39]:
solver.pressure[:,0]

array([2939.50187493, 2668.28999457, 2027.00234799, 2771.23371136,
       2577.92908907, 1952.50786727, 2620.18362869, 2434.76419006,
       1903.03013542])

In [40]:
solver.pressure[:,1]

array([2827.19360194, 2453.37495845, 1679.69190357, 2633.8776444 ,
       2356.82240694, 1620.93213363, 2478.35917283, 2218.48123594,
       1585.04561042])

In [41]:
solver.pressure[:,2]

array([2685.96887892, 2257.21089587, 1490.28966936, 2474.01739563,
       2161.78564617, 1443.64488852, 2315.3938042 , 2027.44698911,
       1415.13438794])

In [42]:
solver.pressure[:,-1]

array([1365.08946949, 1208.77935611, 1037.27110684, 1235.89118108,
       1159.15369464, 1005.22396683, 1112.57469638, 1042.85839144,
        981.60898913])