In [2]:
import numpy as np

In [3]:
import sys
sys.path.append(r'C:\Users\javid.shiriyev\Documents\respy')

In [4]:
from _grids import RecCuboid
from _fluid import Fluid

In [5]:
from _solver import BoundCond
from _solver import Matrix
from _solver import OnePhase

In [6]:
grid = RecCuboid(dims=(4000,100,100),num=(4,1,1))

In [7]:
grid.set_depth([2059,1559,1059,559])
grid.set_poro(0.25)
grid.set_perm(15)

In [8]:
grid.depth

array([[2059.],
       [1559.],
       [1059.],
       [ 559.]])

In [9]:
grid.xperm

array([[15.],
       [15.],
       [15.],
       [15.]])

In [10]:
grid.poro

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])

In [11]:
water = Fluid(density=62.4,viscosity=1)

In [12]:
water.viscosity

1

In [13]:
bcond = BoundCond('xmax',press=500)

In [14]:
sol = OnePhase(grid,water,bconds=(bcond,))

In [15]:
sol.set_time(1,nstep=50)

In [16]:
sol.initialize(2309,1000,1e-5)

In [17]:
tmatrix = sol.Tmatrix()

In [18]:
tmatrix.todense()*sol.trans2field

matrix([[ 0.94924359, -0.94924359,  0.        ,  0.        ],
        [-0.94924359,  1.89848718, -0.94924359,  0.        ],
        [ 0.        , -0.94924359,  1.89848718, -0.94924359],
        [ 0.        ,  0.        , -0.94924359,  0.94924359]])

In [19]:
sol.Amatrix().todense()*sol.trans2field

matrix([[25.0000024,  0.       ,  0.       ,  0.       ],
        [ 0.       , 25.0000024,  0.       ,  0.       ],
        [ 0.       ,  0.       , 25.0000024,  0.       ],
        [ 0.       ,  0.       ,  0.       , 25.0000024]])

In [20]:
sol.Jmatrix().todense()*sol.trans2field

matrix([[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.89848718]])

In [21]:
sol.Qvector().todense()*sol.volume2field

matrix([[  0.        ],
        [  0.        ],
        [  0.        ],
        [949.24359084]])

In [22]:
sol.Gvector(tmatrix)*sol.volume2field

array([[ 2.05677175e+02],
       [-9.89627705e-14],
       [ 9.89627705e-14],
       [-2.05677175e+02]])

In [23]:
tmatrix.dot(sol.grid.depth)

array([[ 2.25610666e-08],
       [ 0.00000000e+00],
       [ 3.30872245e-24],
       [-2.25610666e-08]])

In [24]:
sol.grid.depth

array([[2059.],
       [1559.],
       [1059.],
       [ 559.]])

In [25]:
sol.pinit

array([[891.66259506],
       [674.98778519],
       [458.31297532],
       [241.63816544]])

In [26]:
sol.solve()

0 time step is complete...
1 time step is complete...
2 time step is complete...
3 time step is complete...
4 time step is complete...
5 time step is complete...
6 time step is complete...
7 time step is complete...
8 time step is complete...
9 time step is complete...
10 time step is complete...
11 time step is complete...
12 time step is complete...
13 time step is complete...
14 time step is complete...
15 time step is complete...
16 time step is complete...
17 time step is complete...
18 time step is complete...
19 time step is complete...
20 time step is complete...
21 time step is complete...
22 time step is complete...
23 time step is complete...
24 time step is complete...
25 time step is complete...
26 time step is complete...
27 time step is complete...
28 time step is complete...
29 time step is complete...
30 time step is complete...
31 time step is complete...
32 time step is complete...
33 time step is complete...
34 time step is complete...
35 time step is complete...
36

In [28]:
sol.pressure[:,-1]

array([916.11443552, 725.17545885, 567.20957292, 444.53621207])